# Site settings
title: 'Michel'
description: ''
baseurl: '/surveille-michel'
url: 'https://mwanheda.github.io'

collections:
  - steps

# Build settings
include: ['_steps', '_pages']
defaults:
  - scope:
      path: 'images/concerns'
    values:
      concern: true
  - scope:
      path: 'images/steps'
    values:
      step: true
kramdown:
  input: GFM
